name: Deploy

on:
  workflow_run:
    workflows: ["Build and Test"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          envs: APP_PORT
          script: |
            # Install Docker if not there
            if ! command -v docker &> /dev/null
            then
              sudo apt-get update
              sudo apt-get install -y docker.io docker-compose-plugin
            sudo systemctl enable -now docker
            sudo usermod -aG docker $USER
            fi
            
            mkdir -p ~/festivallines
            cd ~/festivallines
            if [ -d ".git"]; then
              git pull origin main 
            else
              git clone https://github.com/JakeRyanPlatt/FestivalLines.git .
            fi
            export APP_PORT=$APP_PORT
            docker compose up -d --build
          env:
            APP_PORT: ${{ secrets.APP_PORT }}