<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
       <TargetFramework>net10.0</TargetFramework>
       <Nullable>enable</Nullable>
       <ImplicitUsings>enable</ImplicitUsings>
       <InvariantGlobalization>true</InvariantGlobalization>
       <ApplicationUrl>http://localhost:5058</ApplicationUrl>
       <UserSecretsId>68fb2b61-8c3c-4517-b532-09952eb4788a</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.*">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.*" />
    </ItemGroup>

    <ItemGroup>
      <InternalsVisibleTo Include="FestivalLines.Tests" />
    </ItemGroup>

</Project>